-- Reference schema. The dependency-free API applies the same schema from app.py.
-- Use this file when moving to PostgreSQL or another database adapter.
CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, role TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, phone TEXT, email TEXT, area TEXT, source TEXT, type TEXT, size_range TEXT, budget_range TEXT, style TEXT, needs_summary TEXT, owner_id INTEGER, status TEXT NOT NULL, last_contact_at TEXT, next_follow_up_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE cases (id INTEGER PRIMARY KEY, name TEXT NOT NULL, customer_id INTEGER, designer_id INTEGER, site_manager_id INTEGER, address TEXT, stage TEXT NOT NULL, progress INTEGER NOT NULL, budget_range TEXT, next_action TEXT, due_at TEXT, risk_status TEXT, notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE tasks (id INTEGER PRIMARY KEY, title TEXT NOT NULL, case_id INTEGER, assignee_id INTEGER, priority TEXT NOT NULL, status TEXT NOT NULL, due_at TEXT, next_action TEXT, created_by INTEGER, created_at TEXT NOT NULL, completed_at TEXT);
CREATE TABLE schedules (id INTEGER PRIMARY KEY, source TEXT, event_date TEXT NOT NULL, event_time TEXT, title TEXT NOT NULL, category TEXT, case_id INTEGER, location TEXT, owner_id INTEGER, confirmation_status TEXT NOT NULL, notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE portfolios (id INTEGER PRIMARY KEY, name TEXT NOT NULL, case_id INTEGER, category TEXT, style TEXT, size TEXT, area TEXT, year TEXT, design_idea TEXT, public_status TEXT NOT NULL, publish_status TEXT NOT NULL, created_by INTEGER, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE drafts (id INTEGER PRIMARY KEY, kind TEXT NOT NULL, channel TEXT NOT NULL, source_type TEXT, source_id INTEGER, content TEXT NOT NULL, status TEXT NOT NULL, created_by_ai INTEGER NOT NULL, reviewed_by INTEGER, reviewed_at TEXT, published_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE audit_logs (id INTEGER PRIMARY KEY, actor_id INTEGER, action TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id INTEGER, before_json TEXT, after_json TEXT, created_at TEXT NOT NULL);
